### ISSUE TITLE
International soccer tracking with one entity

### ISSUE THREAD

**Issue by bepsoccer** [vasqued2/ha-teamtracker#102]
It would be really cool if we could make it so international soccer could be configured as one entity and query all the "leagues" the games wold be found at automatically rather than having to configure an entity for ever type of game; i.e. friendlies, tournaments, WC qualifying.  For example USA's possible leagues for game are shown here, https://sports.core.api.espn.com/v2/sports/soccer/teams/usa/leagues

**Comment by vasqued2** [comment]
Unfortunately this is much more complicated than just getting a list of leagues.  For now, I'd recommend just copying and pasting the YAML and modifying it and then using a conditional card or an auto-entities card to display the cards with events coming up.
