### ISSUE TITLE
TENNIS OPTION DON'T WORK GOOD

### ISSUE THREAD

**Issue by janfajessen** [vasqued2/ha-teamtracker#103]
The Tennis option no longer indicates that the match is started (IN) and neither does the result.  It was very useful to me because I use an automation when it starts, because tennis normally does not have a fixed schedule, it is played when the previous match ends, which can take a long time.  Let's see if it can be fixed.  I say again that you have done a magnificent job, keep up the good work!

**Comment by vasqued2** [comment]
It's a problem with the ESPN Tennis API.   It is horribly inconsistent.  Details in the known API Defects section of the Wiki.

https://github.com/vasqued2/ha-teamtracker/wiki/Known-Defects-in-the-ESPN-API

**Comment by janfajessen** [comment]
Ok, I hadn't read it.  I hope they fix the API and it works like before again.  Thank you
