### ISSUE TITLE
Add CFL to your API list

### ISSUE THREAD

**Issue by Albuca** [vasqued2/ha-teamtracker#104]
Figure its a longshot, but couldn't hurt to ask!

It appears that the CFL does exist as far as ESPN is concerned (or at least, I have been unable to find any CFL team on their website), and therefore cannot be tracked using your integration.

The CFL does however, have its own API and does allow for an API key to be requested for use by individuals.

What are the chances that your integration can be easily modified, and add this different API to the list?

API documentation: http://api.cfl.ca/docs
Key Request: http://api.cfl.ca/key-request

**Comment by vasqued2** [comment]
ESPN has an API.  Use a Custom API Configuration.  

Details in the README and here:  https://github.com/vasqued2/ha-teamtracker/wiki/Custom-API-Configurations
```
- platform: teamtracker
  league_id: "XXX"
  team_id: "WBB"
  sport_path: "football"
  league_path: "cfl"
  name: "Blue Bombers"
```

**Comment by Albuca** [comment]
Right on, thanks @vasqued2!

**Comment by Albuca** [comment]
It looks like ESPN has moved the CFL endpoint over to TSN: [Link to comment](https://gist.github.com/akeaswaran/b48b02f1c94f873c6655e7129910fc3b?permalink_comment_id=4587458#gistcomment-4587458)
> Does anyone has any idea why ESPN doesn't return any events for the new CFL season? It worked for the previous one. Here are the URLs that I've used which are basically the same, just the dates parameter has a different value:
> 
> 1. [2022](https://site.api.espn.com/apis/site/v2/sports/football/cfl/scoreboard?lang=en&region=us&calendartype=blacklist&limit=300&dates=2022&seasontype=2&week=1)
> 2. [2023](https://site.api.espn.com/apis/site/v2/sports/football/cfl/scoreboard?lang=en&region=us&calendartype=blacklist&limit=300&dates=2023&seasontype=2&week=1)
> 
> EDIT: In case someone else is wondering about this, it seems that ESPN has moved their CFL scores/schedule to a partially owned subsidiary, [The Sports Network](https://www.tsn.ca/). The schedule is provided by [Bell Media](https://www.bellmedia.ca/) and here is an [example](https://stats.sports.bellmedia.ca/sports/football/leagues/cfl/schedule/subset/dates?dateOrId=5&toAdd=0) of a request to fetch the first week schedule.

With this change, is TeamTracker able to access the API endpoint, or am I SOL this season?

**Comment by vasqued2** [comment]
Unfortunately, the JSON structure of new API is completely different from ESPNs and is not compatible with TeamTracker.  Sorry.
