### ISSUE TITLE
Team abbr isn’t a unique value in the api

### ISSUE THREAD

**Issue by xavierxxiii** [vasqued2/ha-teamtracker#108]
I have several trackers set up for Manchester United whose Team abbr is MAN. One of them tracks the English League Cup. Apparently the team Mansfield also have MAN as their Team abbr so their next fixture is showing up on that tracker. 

Would it be possible to give us the option to use Team ID as I’m assuming that would be a unique value?

**Comment by vasqued2** [comment]
Just getting back from vacation.  I'll add this in the next release.

**Comment by vasqued2** [comment]
I added support for the team id.  

It doesn't seem like it's completely unique across sports but I think it is unique within a sport.  See if it works and let me know.

**Comment by xavierxxiii** [comment]
Just tested and it seems to be working fine. It's off season so can't test every competition but I think we can close this. Makes sense that it's not unique across sports because it's only 3 digits but this is workable. Thanks for the fix. Hope your vacation was great.
