### ISSUE TITLE
Feature request - timed team rotation within the card

### ISSUE THREAD

**Issue by bam7** [vasqued2/ha-teamtracker#112]
I was wondering if anyone might have some advice on how I might be able to rotate multiple team sensors within one card.   Like maybe every two minutes or something.   Basically if I can only allocate space for one card, how tough would it be to add multiple team sensors to the same card and have the game info cycle thru?   Any thoughts?

**Comment by vasqued2** [comment]
You might be able to do something with [conditional cards](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Conditional-Cards-to-Hide-NOT_FOUND-Status) or [auto entities](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Auto-Entities-Card-to-Hide-NOT_FOUND-Status) and swap cards based on the current time.

**Comment by vasqued2** [comment]
Closing as this will not be supported in the sensor itself.
