### ISSUE TITLE
Top 25 Rank Request

### ISSUE THREAD

**Issue by hamboneaf** [vasqued2/ha-teamtracker#121]
I would like to display the Top 25 in college football or basketball on a dashboard. I know the data is available but I am just not knowledgeable enough to get it into HA. Any help would be appreciated or an add on to TeamTracker would be awesome.

**Comment by vasqued2** [comment]
[kbrown01](https://community.home-assistant.io/u/kbrown01/summary) has done a lot of work to pull in standings from the ESPN Standings APIs.  

Here's a thread with a lot of the details.
[https://community.home-assistant.io/t/sports-standings-and-scores/547094](https://community.home-assistant.io/t/sports-standings-and-scores/547094)

And this one has some additional details/examples.
[https://community.home-assistant.io/t/real-time-sports-scores-w-teamtracker-and-teamtracker-card-beta/456923](https://community.home-assistant.io/t/real-time-sports-scores-w-teamtracker-and-teamtracker-card-beta/456923)
