### ISSUE TITLE
Sensor unavailable: sensor.bulls

### ISSUE THREAD

**Issue by thunderjunky** [vasqued2/ha-teamtracker#130]
Hi everybody, 
my TeamTracker has stopped working since the last update. It says Sensor unavailable: sensor.bulls without havent changed anything.
Update Failure?

**Comment by vasqued2** [comment]
What version are you on?  Set up w/ UI or YAML?  If YAML, what YAML are you using?  Anything in the logs?

**Comment by thunderjunky** [comment]
This is from my configuration.yaml
#Teamtracker

    platform: teamtracker
    league_id: “NFL”
    team_id: “SEA”
    name: “seahawks”
    api_language: en

    platform: teamtracker
    league_id: “NBA”
    team_id: “CHI”
    name: “bulls”
    api_language: en

    platform: teamtracker
    league_id: “NFL”
    team_id: “PHI”
    name: “eagles”
    api_language: en

and this from my dashboard:
type: custom:teamtracker-card
entity: sensor.eagles
outline: true
outline_color: ‘#ffe500’

I am on Version v.0.11.0

**Comment by vasqued2** [comment]
It looks like you are using Open Quotes and Closed Quotes around your strings instead of Double Quotes for both.  Take out the quotes and see if it works.

**Comment by thunderjunky** [comment]
I tried it like this:

  - platform: teamtracker
    league_id: 'NBA'
    team_id: 'CHI'
    name: 'bulls'
    api_language: en

Same problem

**Comment by thunderjunky** [comment]
same result with this one:
  - platform: teamtracker
    league_id: NBA
    team_id: CHI
    name: bulls
    api_language: en

**Comment by vasqued2** [comment]
First, just try to re-download in HACS.

If that doesn't fix it, turn on debugging by including the following in your configuration.yaml file and tell me what shows up in your logs.

```
logger:
  logs:
    custom_components.teamtracker: debug
```

**Comment by thunderjunky** [comment]
Where should I find the logs? I found nothing in my log files concerning team tracker

**Comment by vasqued2** [comment]
Settings -> System -> Logs

Then you can search for `teamtracker` in the full log.

**Comment by thunderjunky** [comment]
The only Log concerning Teamtracker is the following:

Logger: homeassistant.config
Source: config.py:1483
First occurred: 7. Januar 2024 um 23:19:32 (3 occurrences)
Last logged: 7. Januar 2024 um 23:19:32

Platform error: switch - No module named 'custom_components.teamtracker.switch'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1483, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.teamtracker.switch'

**Comment by vasqued2** [comment]
Those errors are not coming from the teamtracker sensor.

Remove the sensor from HACS.  Remove sensor from YAML config.  Reboot.  Delete any inactive teamtracker sensors.  Reboot.  Search the log for teamtracker.  There should be none.  Confirm this is true.

Reinstall teamtracker from HACS.  Reboot.  Add sensors to YAML config.  Reboot.  Search log for teamtracker.  Post any logs.
