### ISSUE TITLE
Configuration via the "Configuration->Integrations" section of the Home Assistant UI

### ISSUE THREAD

**Issue by Dibelco** [vasqued2/ha-teamtracker#135]
There is no "Configuration->Integrations" 
Only Settings->Integrations, but there is no Team Tracker Card. Only in Devices.
And Team Tracker Card cannot be added anymore to the dashboard.
Or is there a workaround?

**Comment by vasqued2** [comment]
I am not following.  Can you post some screen captures?

**Comment by Dibelco** [comment]
wrong implementation
