### ISSUE TITLE
Problems with friendly FIFA matches

### ISSUE THREAD

**Issue by zeroskrull** [vasqued2/ha-teamtracker#140]
Hi, Im using this for friendly matches of Peru (1st time doing this exact one) and im getting an error, is already 26, the match is today and nothing yet.

- platform: teamtracker
    league_id: XXX
    team_id: PER
    sport_path: soccer
    league_path: fifa.friendly
    name: peru_friendly
    
![imagen](https://github.com/vasqued2/ha-teamtracker/assets/69728942/386adf1d-7697-49ac-ab85-4aa7b4b3982f)

And match is already up in espn web

![imagen](https://github.com/vasqued2/ha-teamtracker/assets/69728942/67116882-98c8-44f7-bc2c-5fbef2832ada)

**Comment by vasqued2** [comment]
It looks like you have everything set up correctly.  The API has a cap of returning at max 25 games.  If there are more scheduled for a single day, it only returns the first 25 and drops the rest.  It looks like there are 35 fifa friendlies scheduled for today and unfortunately it looks like Peru's is #35 in the list.  Unfortunately it is getting cut off.

Not usually an issue as most leagues have less than 50 teams.  Unfortunately there are a lot more fifa teams playing friendlies at the same time today.

**Comment by zeroskrull** [comment]
Oh that sucks, thanks for the answer, so if this is an API problem theres no way to get the info, like a bypass method?.
Thanks

**Comment by vasqued2** [comment]
You would have to explicitly override the API default limit set by ESPN.  I am sure they put them in place for a reason.  I don't want to abuse it and give them a reason to shut them down or take away access.
