### ISSUE TITLE
Feature Request: Addition of F1 Race Flag Tracking?

### ISSUE THREAD

**Issue by Seaniau** [vasqued2/ha-teamtracker#141]
Sorry to raise this as an ‘issue’, I [posted on the HA forum](https://community.home-assistant.io/t/real-time-sports-scores-w-teamtracker-and-teamtracker-card-beta/456923/535?u=seaniau) but got no response.

Would it be possible to monitor race flags using this integration?
The information seems to be available on ESPN’s site but is located in the [calendar entry](https://www.espn.com/f1/schedule) for each race rather than a central place such as the ESPN Home Page.

The screenshot in my forum post shows an example, I can’t copy it here on Mobile.

An entity that changes live with Green, Yellow, Red and Checker flags would allow for some incredibly immersive lighting automations!

Thanks,
Sean

**Comment by vasqued2** [comment]
I've confirmed the API does not return an indicator when under Yellow.  There is nothing I can do.
