### ISSUE TITLE
Struggling with f1 not found

### ISSUE THREAD

**Issue by Heinvt01** [vasqued2/ha-teamtracker#142]
I cant find any abbreviations for f1 only the three letter driver abbreviations Ex. VER and it all says NOT_FOUND

what do i need to enter in the team/athelte* field for redbull and max verstappen. Or am I missing the point? Will it only show data during a session?

And i would like to co ask for flags during the race if possible

**Comment by vasqued2** [comment]
VER should work.  I think you just have to wait until closer to the race.

Right now the API is returning event information for the MSC Cruises Japanese Grand Prix but the drivers aren't listed yet.  I know for some series the driver info doesn't get populated until the starting grid is finalized.  I believe for F1 it returns info beginning with the free practice sessions.  If so, the driver info should show up by that time.  I don't know when the driver lineups are considered final for a race to know when to expect them to be populated by the API.  

Just know VER should work.  You aren't doing anything wrong.  If you get to the free practice sessions and still aren't getting a hit, let me know and I will look again.

**Comment by vasqued2** [comment]
Also, it's not mine but you might want to look at this card.  It is specific to F1, uses an F1-specific API so it can do a lot more F1 specific things than the standard ESPN API I use does.

[ https://github.com/marcokreeft87/formulaone-card]( https://github.com/marcokreeft87/formulaone-card)

**Comment by vasqued2** [comment]
Confirmed VER is working.
