### ISSUE TITLE
Display current game for playsoffs- any teams 

### ISSUE THREAD

**Issue by boojew** [vasqued2/ha-teamtracker#147]
So, the Habs season is done and of course they didn’t make the playoffs. So, now I’d love to know if I could use the this to view any NHL team currently playing?

**Comment by phurth** [comment]
I agree, this would be a nice feature. As a supported of teams that often don't make playoffs, or get bounced early, I'd love to be able to continue to follow teams that are still in.

**Comment by vasqued2** [comment]
Try using the wildcard value `*` for the team name.  I believe the sensor will then show whatever current game is in progress (if there is one) or the next schedule playoff game (if there isn't one in progress.

The record displayed comes from ESPN and I can't change it.

**Comment by vasqued2** [comment]
I have confirmed using * for the team name will behave as I have described above.  It looks like I may be able to pull in the series records but it will require an enhancement to the sensor to do so.  I will leave this open and see if I can get to it in the future.

**Comment by vasqued2** [comment]
v0.13.0 will return the attribute `series_summary` which contains the status of the playoff series, including the record in the series.

v0.13.0 of the TeamTracker Card will display the series summary at the top if the card if it is returned.
