### ISSUE TITLE
Racing only seems to work if a driver is selected

### ISSUE THREAD

**Issue by phurth** [vasqued2/ha-teamtracker#148]
Hi! It appears that the integration only works for racing leagues if a driver is chosen at setup.

Desired Behavior:
If no driver is selected, the integration would display the 1st and 2nd place drivers, regardless who they are.

Current Behavior:
If no driver is selected when setting up the integration, the API message indicated no competition is scheduled, so nothing ever is displayed.

I tested with Nascar and Indycar, so I don't know if this behavior is consistent across all racing types. I also don't know what happens if you do select a driver, but they don't actually participate in a particular race.

I'm not sure if this is a bug or an enhancement request. Thanks!

**Comment by vasqued2** [comment]
What are you putting in for Team/Athlete?  You should use the wildcard indicator `*` to get it to match to any driver and show the first/second place driver.

**Comment by vasqued2** [comment]
I've confirmed `*` works for F1 and NASCAR.  What value do you have for the Team/Athlete?

**Comment by phurth** [comment]
I reconfigured using the wildcard (*) and it work as expected. Thanks! I may have missed it, but I don't recall seeing that in the documentation.

**Comment by vasqued2** [comment]
Glad it is working.  I will add a link in the Team ID section to reference the Wildcard section.  

[https://github.com/vasqued2/ha-teamtracker?tab=readme-ov-file#use-of-a-wild-card-in-place-of-athletes-name](https://github.com/vasqued2/ha-teamtracker?tab=readme-ov-file#use-of-a-wild-card-in-place-of-athletes-name)
