### ISSUE TITLE
Kickoff Time an hour ahead

### ISSUE THREAD

**Issue by tempus2016** [vasqued2/ha-teamtracker#149]
I set up automations for football notifications but they always send 2 hours before the game, not 1 hour like I set. The game kicks off at 8pm UK time but shows kickoff in an hour. Any help would be great. 

![IMG_4442](https://github.com/vasqued2/ha-teamtracker/assets/40920327/a32f173c-a814-4465-9d40-899ae19bdede)
![IMG_4443](https://github.com/vasqued2/ha-teamtracker/assets/40920327/221df79d-8d7e-489f-b240-7e8b13c98a0f)
![IMG_4444](https://github.com/vasqued2/ha-teamtracker/assets/40920327/c3e82826-c46c-4a4e-87d7-8082acbcfbbd)
![IMG_4445](https://github.com/vasqued2/ha-teamtracker/assets/40920327/591f511d-d3cd-4d44-b083-7d6361d599fa)
![IMG_4446](https://github.com/vasqued2/ha-teamtracker/assets/40920327/3c218e86-1d3f-41eb-991f-9290c923b76f)

**Comment by Waank1** [comment]
I have a similar problem.  I live in the USA - Central Time Zone, but the time in the entity attributes is EDT, is there a way to change that?

**Comment by vasqued2** [comment]
I use an external function to "humanize" the time so it is an approximation, not exact.  Rather than checking for the exact value "in an hour" you should probably use a template to trigger when kickoff_time changes to contain the word "minutes".  Or you could use the date attribute and compare it to the current time.  If you do that, you'd have to localize it.

**Comment by vasqued2** [comment]
It looks like the easiest way to get it to work they way you want is trigger it when it changes FROM "in an hour" to the minute countdown.  This will happen sometime between 50-60 minutes before kickoff, which sounds like closest to what you want.  See the thread below for more details on how everything works and there is YAML in the last post with an example.

[https://github.com/vasqued2/ha-teamtracker/issues/93](https://github.com/vasqued2/ha-teamtracker/issues/93)
