### ISSUE TITLE
euro2024

### ISSUE THREAD

**Issue by braticks** [vasqued2/ha-teamtracker#159]
Any chance to track euro 2024 teams?

**Comment by vasqued2** [comment]
Use custom configuration w/ `sport_path` set to `soccer` and `league_path` set to `UEFA.EURO`

**Comment by clempat** [comment]
You can do it by setting a custom League.

As team put the team id. You can find it in the url on espn. For example Germany is `481` knowing the url is https://www.espn.co.uk/football/team/_/id/481/germany.

Then in the second screen you need to enter `soccer` as sport and `uefa.euro` as league.

Maybe the wording is a bit different as I have an other language but hopefully this helps you already.
