### ISSUE TITLE
Euro 2024.

### ISSUE THREAD

**Issue by schumi2309** [vasqued2/ha-teamtracker#160]
Hello, 

is there anything planned for euro 2024?
Thanks.

**Comment by vasqued2** [comment]
It should.

Use custom configuration w/ sport_path set to soccer and league_path set to UEFA.EURO

**Comment by schumi2309** [comment]
should I do it through the sensor.yaml or through the integration?

I tested this using sensor.yaml but it doesn't work.

- platform: teamtracker
  league_id: "EUR"
  sport_path: "soccer"
  league_path: UEFA.EURO
  name: "Euro 2024"

An example ?

**Comment by vasqued2** [comment]
This will set up a sensor for Italy for example

```
- platform: teamtracker
  league_id: "XXX"
  team_id: "ITA"
  sport_path: "soccer"
  league_path: "UEFA.EURO"
  name: "euro_ita"
```

This will set up a sensor that will pivot to whichever game is next or is underway.
```
- platform: teamtracker
  league_id: "XXX"
  team_id: "*"
  sport_path: "soccer"
  league_path: "UEFA.EURO"
  name: "euro_all"
```

**Comment by schumi2309** [comment]
ok, it works...Thanks.
And is it possible to have the classification by group? is there a card to do this?
I managed to achieve something, but it only includes the first group, and not the following ones!
thanks in advance.

**Comment by vasqued2** [comment]
It doesn't look like it.  The API indicates the current games are in the group stage but it doesn't indicate which group they are in.  It looks like you'd have to use something like a Vertical or Horizontal Stack Card to manually group whichever ones you wanted together and then change it up once the group stage is over.

**Comment by schumi2309** [comment]
Let's say I would like to have the complete table but I can only display the first group.
![Capture d’écran 2024-06-17 à 11 13 40](https://github.com/vasqued2/ha-teamtracker/assets/47976917/09e0dd9a-8c09-43e4-adae-b0ea0fb3431b)

How to choose the other groups?

![Capture d’écran 2024-06-17 à 11 12 18](https://github.com/vasqued2/ha-teamtracker/assets/47976917/80c278cf-c6d7-4f6a-95e4-9772fd4bb022)

**Comment by vasqued2** [comment]
This isn't a Team Tracker issue. If you post on this thread or to the linked repository, you should find someone to help you.

[https://community.home-assistant.io/t/sports-standings-and-scores/547094](https://community.home-assistant.io/t/sports-standings-and-scores/547094)

**Comment by Chumba** [comment]
Just chiming in to say I was able to configure Euro team tracker in HA UI by using the Custom option for league, and the ESPN link's team ID as the "Team/Athlete", for example Switzerland's team profile page is: "https://www.espn.com/soccer/team/_/id/475/switzerland"

I entered 475 into the Team/League field and it worked like a charm

**Comment by iroQuai** [comment]
It works, but sometimes it's a bit slow. I've seen two replays already and then the lights kick in to celebrate the goal. Other triggers work fine like start and end game... Probably it's the ESPN intern that doesn't click +1 quick enough or something? :)

**Comment by vasqued2** [comment]
Euro 2024 over.
