### ISSUE TITLE
Showing upcoming games by team for alle leagues / competitions

### ISSUE THREAD

**Issue by irqnet** [vasqued2/ha-teamtracker#172]
I've just added successfully the teamtracker card for HA to show the upcoming games for my favorite team.

Obviously it's showing only games for the configured league, but not considering other games besides the league (e.g Bundesliga is shown, but not German DFB Pokal.)

Any option to configure the integration to fetch all games for a club in a row?

**Comment by vasqued2** [comment]
The API is by league, not team.  You have to set up a different sensor for each league.  

The [Wiki](https://github.com/vasqued2/ha-teamtracker/wiki) has entries that show how you can hide cards using the [conditional](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Conditional-Cards-to-Hide-NOT_FOUND-Status) card or [auto-entities card](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Auto-Entities-Card-to-Hide-NOT_FOUND-Status) to only show cards of a certain state or other characteristics.
