### ISSUE TITLE
Acabo de actualizar y la tarjerta no me va

### ISSUE THREAD

**Issue by stellahassio** [vasqued2/ha-teamtracker#174]
tarjeta:
type: custom:teamtracker-card
entity: sensor.team_tracker

error
Errores de configuración detectados:
Custom element not found: teamtracker-card

**Comment by vasqued2** [comment]
borre su caché y actualice

**Comment by vasqued2** [comment]
Prueba v0.14.3-beta1

**Comment by vasqued2** [comment]
Resolved w/ v0.14.3
