### ISSUE TITLE
Issue with soccer fr ligue 1 teams

### ISSUE THREAD

**Issue by WitcherDrake** [vasqued2/ha-teamtracker#178]
The is no data for France lyon soccer teams ligue 1 with id 167.

**Comment by vasqued2** [comment]
When's the game?  Probably too far in the future.  Wait a couple days.

**Comment by WitcherDrake** [comment]
Next game is 09/15, Il'wait but there is data with other ligue 1 teams (ex: 160).
Thanks

**Comment by vasqued2** [comment]
I assume other teams play before 9/15?

**Comment by vasqued2** [comment]
It's FIFA break.  The next upcoming matches won't populate until at least 9/10.

**Comment by WitcherDrake** [comment]
OK I'll wait for 9/10 to see if my team is populate. Thanks
