### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by romquenin** [vasqued2/ha-teamtracker#181]
Could you please edit some "StartTerm" for the french language next time you upload the card:

```
basketball: Astuce = Engagement

football: Démarrer = Engagement

soccer: Commencer = Coup d'envoi

hockey: Lancer de rondelle = Mise en jeu

mma: Commencer = Début du combat

racing: Commencer = Départ de la course
```

![Capture d’écran 2024-09-20 154216](https://github.com/user-attachments/assets/d96c46f6-284f-4cfa-aa8f-8500899daf51)

**Comment by vasqued2** [comment]
Added to v0.14.12
