### ISSUE TITLE
Not finding MLB games

### ISSUE THREAD

**Issue by kpolack** [vasqued2/ha-teamtracker#186]
Added this yesterday and am trying to track Detroit for MLB. DET is showing as not found through 10/3 (even today at 10/5). Tried a * for the team to see what would come up and it pulls the Mets Brewers game from 10/3.

Is there something special that needs to be done to pull in playoff games? Or is the API just acting up?

**Comment by kpolack** [comment]
Looks like the game for today just populated.

**Comment by vasqued2** [comment]
![image](https://github.com/user-attachments/assets/1acab90a-950a-4de3-8d75-fee2f7a37165)
