### ISSUE TITLE
French rugby league / TOUL

### ISSUE THREAD

**Issue by Sebbes84** [vasqued2/ha-teamtracker#188]
Hi,

Thank you for your good job.

In the French rugby league (Top 14), 2 teams have the same initials "TOUL".
- Toulon (https://www.espn.com/rugby/match/_/gameId/599644/league/270559)
- Toulouse (https://www.espn.co.uk/rugby/match/_/gameId/599646/league/270559)

How to differentiate them in a sensor?
I would only like to follow Toulouse.

Thanks.

Seb.

**Comment by vasqued2** [comment]
Try using the team id (25922) instead of the abbreviation.  It happens in some soccer leagues and that's how others have gotten around it.

**Comment by Sebbes84** [comment]
That’s ok. 
Thanks.
