### ISSUE TITLE
No competition scheduled

### ISSUE THREAD

**Issue by romquenin** [vasqued2/ha-teamtracker#189]
Hello, i don't have the game schedule since the last game finished on the 5th of october.

```
api_message: >-
  Cached data: No competition scheduled for 'ARS' between 2024-10-06T13:00Z and
  2024-10-06T15:30Z
```

Before every next game was scheduled properly. Any ideas on what's wrong with the component that seems to be stuck on the day?

Thanks in advance

**Comment by vasqued2** [comment]
FIFA break.  Next game isn't until Oct 19.  The API will return it when it gets closer.
