### ISSUE TITLE
Calendar support

### ISSUE THREAD

**Issue by buyukgaga** [vasqued2/ha-teamtracker#191]
Hello,

First of all, thanks for this great integration.
When using the integration, I need to add separately for my team both for the normal league and for the matches in other European cups and I need to organize automations for these sensor trackers. For example, I need to add separately for the Turkish League (tur.1) and separately for the UEFA European Cup (uefa.europa).
If possible, when I add the team, how about if this data automatically appears on the card and the relevant team's sensor when there is a match in the calendar.

Thank you.

**Comment by vasqued2** [comment]
The ESPN APIs are by league, not by team.  You have to set one up for each league as you noted.  That's the way the APIs work.  I can't change that.

The best way to handle that is to hide the cards if they have a status of NOT_FOUND.

The [wiki ](https://github.com/vasqued2/ha-teamtracker/wiki)has two entries that explain how to use a conditional card or the auto entities card to do this.
