### ISSUE TITLE
Unable to get NBA sensor to work

### ISSUE THREAD

**Issue by schwaboy** [vasqued2/ha-teamtracker#192]
I have this working with NHL, College Football, MLS, English Premier League... but I'm having a really hard time getting it to work with the NBA. 

```
  - platform: teamtracker
    league_id: "NBA"
    team_id: "Utah"
```

For the `team_id` I have tried Utah, utah, UTAH, UTA, uta, Jazz, 26, and utah-jazz.

All of them result in the card showing "Sensor unavailable", except for UTA or uta, which shows the card, but always shows that there is no future game scheduled, even when there is. 

When I look at the [ESPN API for the Utah Jazz](http://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams/Utah), the id is 26, the abbreviation is UTAH, the name is Jazz, and the nickname is utah.

Has anybody been able to make it work?

**Comment by schwaboy** [comment]
Nevermind, I figured it out. The correct id was `26`, however I wasn't noticing it because it creates a different teamtracker sensor every time you change the id. So I had to change my card from `sensor.team_tracker_4` to `sensor.team_tracker_5`.

**Comment by vasqued2** [comment]
You should go back and delete all the other sensors.
