### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by fay000fay** [vasqued2/ha-teamtracker#195]
In the latest version, everything was working fine until a sudden API error occurred.
![微信截图_20241121092304](https://github.com/user-attachments/assets/beadc96f-e088-4b60-af26-c029fd6e783d)

**Comment by vasqued2** [comment]
This generally means a temporary issue on ESPNs side or a problem with your internet.  It’s working for me now.  Still having issues?

**Comment by fay000fay** [comment]
> This generally means a temporary issue on ESPNs side or a problem with your internet. It’s working for me now. Still having issues?

still issue,"API did not return any data for team 'LAL". I tried old version, still error. and my network is fine, cause I can open https://www.espn.com

**Comment by vasqued2** [comment]
The API is still working for me.

What does the direct API call return from your HA server?  
[https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard](https://site.api.espn.com/apis/site/v2/sports/basketball/nba/scoreboard)

![image](https://github.com/user-attachments/assets/197d9bcf-7576-4447-a0d0-de35e59d4932)
