### ISSUE TITLE
Multiple Team Add?

### ISSUE THREAD

**Issue by mermelmadness** [vasqued2/ha-teamtracker#20]
Is it possible to add multiple teams in a single configuration?  For example, for NCAAM, is it possible to add an entire conference?  Or would it be possible to add NFL but have every single team?

**Comment by vasqued2** [comment]
Sorry, you have to set up each team’s sensor individually. 

I know it’s horribly inefficient on the API calls so maybe someday I’ll look into making it more efficient, but it would take a major rewrite and would not be backwards compatible with the existing functionality.

**Comment by vasqued2** [comment]
I’d highly discourage you from doing that.  You would be much better off creating your own rest sensor that makes a single API call and then parse the results of all games than creating hundreds of separate sensors.  During times of multiple games, you would have thousands of API calls going on each minute, which would not be good for you or ESPN.

[See this post](https://community.home-assistant.io/t/real-time-sports-scores-w-teamtracker-and-teamtracker-card-beta/456923/83?u=vasqued2) for details.

**Comment by mermelmadness** [comment]
I'll have to investigate that.  I'm a novice when it comes to JSON construction and RESTful calls.  And being able to parse it in a way that HA will understand.  Tall order.  Thanks for the advice.
