### ISSUE TITLE
NASCAR?

### ISSUE THREAD

**Issue by matthewmarra** [vasqued2/ha-teamtracker#38]
See you have F1 and IRL, which is great. Wondering if we could get NASCAR added?

**Comment by vasqued2** [comment]
The API doesn’t return an image/flag for the drivers so it uses a default error logo, but it should work.  If not, sport_path = racing, league_path = nascar-premier

Trying to decide how to handle before publishing official support.  Probably just use the NASCAR logo for the drivers.  Thoughts?

**Comment by vasqued2** [comment]
Fixed the teamtracker-card to display the driver's initials.  Although not documented, you can type in "NASCAR" for the league and it will work.

**Comment by matthewmarra** [comment]
awesome that's great! meant to get back to you sooner to help but very much appreciate it.
