### ISSUE TITLE
Any chance of adding CONCACAF Soccer?

### ISSUE THREAD

**Issue by Coolie1101** [vasqued2/ha-teamtracker#39]
Any chance of adding CONCACAF Soccer?

https://www.espn.com/soccer/standings/_/league/fifa.worldq.concacaf

**Comment by vasqued2** [comment]
It should support it with a Custom API Configuration.  I would assume the league_path would be fifa.worldq.concacaf

**Comment by Coolie1101** [comment]
Sorry wrong link, it's not just for world cup, but all Concacaf leagues.

**Comment by Coolie1101** [comment]
> Am I missing something?

I am truly sorry, but I am not sure what you are trying to tell me, or how to set it up.
