### ISSUE TITLE
Ranking board

### ISSUE THREAD

**Issue by schumi2309** [vasqued2/ha-teamtracker#47]
Hello,
With this API, does it give us the possibility to make a card with a table of the league classification? that would be nice

**Comment by vasqued2** [comment]
Unfortunately not.  That is a completely different API.

**Comment by schumi2309** [comment]
ok, thanks.

**Comment by vasqued2** [comment]
Someone showed me how you can use a REST sensor an the flex-table-card to create a standings card.

Details in the Wiki here:  [https://github.com/vasqued2/ha-teamtracker/wiki/Standings-Card](https://github.com/vasqued2/ha-teamtracker/wiki/Standings-Card)

Here's an example of what it looks like.
![image](https://user-images.githubusercontent.com/17114183/221385482-2f371a44-1e1b-498f-a731-194c62cd8787.png)

**Comment by imist** [comment]
Awesome stuff!!

You have a small typo in the example code for the tied column of EPL Standings. It says "align: Pts" but should of course be "align: center" as all the other numeric columns.

Thanks for all the work you put into this project @vasqued2 !!

**Comment by schumi2309** [comment]
Yeah, I noticed that already and it's fixed. Thank you for the info.
Don't forget the French modifications.
Have a nice week end.

Le 26 févr. 2023 à 10:35, Michael Stellrot ***@***.***> a écrit :



Awesome stuff!!

You have a small typo in the example code for the tied column of EPL Standings. It says "align: Pts" but should of course be "align: center" as all the other numeric columns.

Thanks for all the work you put into this project @vasqued2<https://github.com/vasqued2> !!

**Comment by imist** [comment]
I am in Sweden so I don’t really care about the French mods ;-)

Nice weekend (what’s left of it) to you too!

Michael

> 26 feb. 2023 kl. 10:38 skrev schumi2309 ***@***.***>:
> 
> 
> Yeah, I noticed that already and it's fixed. Thank you for the info. 
> Don't forget the French modifications. 
> Have a nice week end. 
>
