### ISSUE TITLE
Timeouts not updating

### ISSUE THREAD

**Issue by jcotney** [vasqued2/ha-teamtracker#5]
Most features work great! However during NCAA football games the timeouts do not update to the correct remaining number. There are no errors just always shows three for both teams.

**Comment by vasqued2** [comment]
Thanks.  I’ll monitor during the NFL games today and see if I inadvertently broke the timeouts for everything or if it’s specific to the NCAA.

**Comment by vasqued2** [comment]
I confirmed the timeouts are updating correctly for the NFL games.

It could either be (1) that ESPN is only providing timeout data for some games and I'm displaying the three as a default value even when ESPN doesn't provide a value, or (2) ESPN is incorrectly reporting 3 timeouts the whole time.

Unfortunately, I only have data saved for two college teams at a single point in time from yesterday.  ESPN was supplying timeout data for both of them and both were showing 3 timeouts.  So I know that ESPN is providing timeout data for at least some games.  Just don't know yet if it's for all games and if it is accurate.  I'll have to wait for next weekend to check further.

What games did you notice the problem for?  I have noticed inconsistencies with the data quality depending on the team.  Both teams I looked at were top 10, nationally broadcast games, which obviously have the more reliable data.

**Comment by jcotney** [comment]
First game was Alabama and Texas. Play text and clock were updating nicely. Second game was Auburn and San Jose State. Pretty minor thing overall but thought I would mention.

**Comment by vasqued2** [comment]
Coincidently, Alabama was one of the games I had a single point-in-time data capture from this weekend.

The API returned timeout data that showed both Alabama and Texas had 3 timeouts w/ 4:15 left in the 4th but it looks like ALA didn't call their first timeout until 1:38 left and I don't have a data capture after that point.

I'll watch it more closely this weekend and see if I can track it down, but I suspect ESPN always returned 3 TO's throughout the whole game.  I can't imagine why they would stop sending that info if they were sending it earlier in the game, but I suppose anything is possible.

Appreciate the heads up and I'll watch for it this weekend.

**Comment by vasqued2** [comment]
I was able to confirm w/ tonight's FSU/LOU game that the ESPN API is always sending 3 timeouts for each team.  At this point in the game, both FSU and LOU had only 2 timeouts left but ESPN was still reporting 3.

I'll track a lot of games tomorrow and see they ever send the right values for a college game.  Just weird because they do update the timeout info for NFL games.  For other sports, they don't send anything.

            "down": 4,
            "yardLine": 45,
            "distance": 7,
            "downDistanceText": "4th & 7 at LOU 45",
            "shortDownDistanceText": "4th & 7",
            "possessionText": "LOU 45",
            "isRedZone": false,
            "homeTimeouts": 3,
            "awayTimeouts": 3,
            "possession": "97"
          },
          "status": {
            "clock": 16,
            "displayClock": "0:16",
            "period": 2,
            "type": {
              "id": "2",
              "name": "STATUS_IN_PROGRESS",
              "state": "in",
              "completed": false,
              "description": "In Progress",
              "detail": "0:16 - 2nd Quarter",
              "shortDetail": "0:16 - 2nd"
            }
          },

**Comment by jcotney** [comment]
No worries. Weird they even bother reporting. Maybe give the option to hide timeouts/probability on the card to address?

**Comment by vasqued2** [comment]
Generally if they aren't updating for a sport, ESPN just doesn't send a value, which makes this an outlier.  Timeouts, odds, probability are all like that.  I'm wondering if they realize it's not updating.  Although they don't display timeout info on their website either.

I'm working on a major refactoring of the json parser right now but will keep this open and see if I can create an option to display or hide later.  I like that better than a bunch of one-off specific exceptions for various scenarios that could arise.

Although I haven't tested it, you should be able to edit the card and add something like the following to hide the timeouts for college football if you want to.  Should be able to paste it in the section that is doing all the checks for various sports and toggling things on and off.

```
    if (stateObj.attributes.league.includes("NCAAF")) {
      timeoutsDisplay = 'none';
    }
```

**Comment by vasqued2** [comment]
Added option to the teamtracker_card to hide the timeouts if you want.  Just add the following YAML to your card definition.

```show_timeouts: False```

**Comment by vasqued2** [comment]
Documented this along with other known issues with the ESPN APIs in the Wiki.
