### ISSUE TITLE
Can you also insert the Turkish Süper lig

### ISSUE THREAD

**Issue by akata68** [vasqued2/ha-teamtracker#50]
Can you also insert the Turkish Süper lig
ID: SUPER 
Path: tur.1

https://site.api.espn.com/apis/site/v2/sports/soccer/tur.1/scoreboard

**Comment by vasqued2** [comment]
It's already supported using a Custom API Configuration.  Should be something like this...
```
# Custom Integration - 
  - platform: teamtracker
    league_id: XXX
    team_id: YOUR_TEAM_HERE
    sport_path: soccer
    league_path:  tur.1
```
See [FAQ Question #2](https://github.com/vasqued2/ha-teamtracker/wiki/Frequently-Asked-Questions) or [README ](https://github.com/vasqued2/ha-teamtracker/blob/master/README.md) and let me know if you have any problems getting it to work.

**Comment by vasqued2** [comment]
Closing as tur.1 can be set up with a Custom API Configuration.
