### ISSUE TITLE
Issue with International Soccer  - SERA

### ISSUE THREAD

**Issue by petersoniq** [vasqued2/ha-teamtracker#52]
Hello, can you help me with SERA (Italian Serie A) ?
I can not found correct code for team (approx. AC Milan). In espn.com is visible only code 103.
Thanks.

**Comment by imist** [comment]
Use ”MIL”

**Comment by petersoniq** [comment]
Thank you, work it.

**Comment by vasqued2** [comment]
Just curious where you see code 103.  Every once in a while people refer to team codes as a number, especially soccer, and I’m trying to understand where they are getting them from.

**Comment by vasqued2** [comment]
Closing as resolved.

**Comment by imist** [comment]
I think he found it in the url for Milan:

https://www.espn.com/soccer/team/_/id/103/ac-milan

**Comment by infestonn** [comment]
@imist just curious, how did you find the correct abbr?
