### ISSUE TITLE
Add brand icon

### ISSUE THREAD

**Issue by hudsonbrendon** [vasqued2/ha-teamtracker#6]
You could add an icon for integration, I think the ESPN icon would work.
https://github.com/home-assistant/brands

![image](https://user-images.githubusercontent.com/5201888/189499565-9d571648-1d4c-4358-8ba6-bbacd848ffaa.png)

![image](https://user-images.githubusercontent.com/5201888/189499593-4b298781-42ee-4994-9071-b6086f0c5baf.png)

**Comment by vasqued2** [comment]
Thanks for the link.  I'll see if I can get one added.

**Comment by hudsonbrendon** [comment]
Working perfectly!

![image](https://user-images.githubusercontent.com/5201888/192388892-fd5bb7e5-2cbe-4b13-9584-0fe566fc0fcf.png)

![image](https://user-images.githubusercontent.com/5201888/192389025-f42ae039-27f3-446e-97f5-0f248bb655d6.png)

**Comment by vasqued2** [comment]
Appreciate your help.
