### ISSUE TITLE
ESPN API Explore page not found

### ISSUE THREAD

**Issue by jgeorge1983** [vasqued2/ha-teamtracker#71]
Not necessairly your issue, but whenever i follow the link to the API page i get page not found, http://www.espn.com/apis/devcenter/io-docs.html
Is this something im not doing correct?

**Comment by jgeorge1983** [comment]
Think i figured it out, you can just use the deets from the standard link rather than the API, so for carabao cup, i just used eng.league_cup.  And that seemed to work
https://www.espn.co.uk/football/fixtures/_/league/eng.league_cup

**Comment by vasqued2** [comment]
I'm not sure where the link is that you are referring to.

Lmk and I'll update it.

**Comment by jgeorge1983** [comment]
the mesiah himself!! its the http://www.espn.com/apis/devcenter/io-docs.html page, the _API Explorer_ link, it may just be me but i get "Page not Found"  as i say though, i figured out you can use the actual link for the league without needed the API.

**Comment by vasqued2** [comment]
Ha ha.

Looks like ESPN may have shut down their entire API Dev Center site.  Hopefully that's not a foreshadowing off more things to come.

I'll monitor for a couple days.  If it's permanently gone, I'll update the wiki to give more details on how to use the process you used.  The site just made it easier.

**Comment by jgeorge1983** [comment]
Think i got lucky tbf.  

While i have your attention, there is a game on 1st March, UK FA Cup, Mancester United.  My card says no upcoming games through 19/02/2023
Is the game just to far ahead/future of the card?

**Comment by vasqued2** [comment]
Probably.  It’s possible you have something set up wrong but you won’t be able to tell until it gets closer to the event.  The api doesn’t return events that far out.  That’s why you are getting that message.

**Comment by jgeorge1983** [comment]
Thanks, I figured I was looking to far ahead.  I'll keep an eye on it.

Thanks for the work, its a great integration!

**Comment by vasqued2** [comment]
Updated the Wiki to note that ESPN took down their API DevCenter site.
