### ISSUE TITLE
German Bundesliga and Champions League not working well

### ISSUE THREAD

**Issue by Deinjo** [vasqued2/ha-teamtracker#72]
Hello,

i have tried out to configure my favorite club "Borussia Dortmund" of the German Bundesliga and also for the ChampionsLeague.

I checked the ESPN website and i found out that 124 ist the team_id for my club. I checked the api and i get some results:
http://site.api.espn.com/apis/site/v2/sports/soccer/ger.1/teams/124
http://site.api.espn.com/apis/site/v2/sports/soccer/uefa.champions/teams/124

i use this configuration in my yaml:
  - platform: teamtracker
    league_id: "BUND"
    team_id: "124"
    name: "bl_bvb"

  - platform: teamtracker
    league_id: "CL"
    team_id: "124"
    name: "cl_bvb"

But for both configs i get as result API-Message = "No competition scheduled for '124' between 2023-02-14T00:00Z and 2023-02-20T00:00Z". But this is not true.
E.g. today 15th of Feb 23 there is the CL-Match ageainst FC Chelsea. This is also visible on the ESPN Website.

I have also tried to config the club manually. But result is the same.
  - platform: teamtracker
    league_id: XXX
    team_id: 124
    sport_path: soccer
    league_path:  uefa.champions
    name: tt_custom_cl_bvb   

I have activated the customer logging and there is the request:
http://site.api.espn.com/apis/site/v2/sports/soccer/uefa.champions/scoreboard?lang=en&dates=20230214-20230220

If i checked the json file manual in a editor i find this result:
{"id":"656852","uid":"s:600~l:775~e:656852","date":"2023-02-15T20:00Z","name":"Chelsea at Borussia Dortmund","shortName":"CHE @ DOR","season":{"year":2022,"type":11304,"slug":"round-of-16"},

This does not seem to be evaluated correctly.

Is there something wrong in my configuration or it's a bug in the teamtracker?

Greetings from Dortmund
Deinjo

**Comment by vasqued2** [comment]
Use the team abbreviation DOR that shows on the ESPN website, not the ID number.

I know using team_id here is confusing but it's a carryover from the NFL sensor this was originally based on and changing it would break a ton of existing sensors.

**Comment by Deinjo** [comment]
Perfect. With "DOR" it works very well.

Many Thx
