### ISSUE TITLE
REQUEST: Add XFL support?

### ISSUE THREAD

**Issue by kylepyke** [vasqued2/ha-teamtracker#84]
What are the chances of adding XFL support as part of the default integration?

Thanks!

**Comment by vasqued2** [comment]
XFL is supported.  Just use a Custom API Configuration.  
```
sport_path: football
league_path: xfl
```

It will behave the same as a league supported natively once you set it up.

**Comment by kylepyke** [comment]
Oh wow, that was super easy, thanks! For anyone else that finds this, and wants to use the HA UI, you have to fill "XXX" in the league field, then it will trigger a second dialog for the sport_path and league_path..

**Comment by vasqued2** [comment]
Glad it worked for you!

Closing as resolved.
