### ISSUE TITLE
Golf Player

### ISSUE THREAD

**Issue by brhahlen** [vasqued2/ha-teamtracker#86]
Just found this card and am trying to figure out how I can get indiviual Golf players to track.
I've tried with:
```
- platform: teamtracker
  league_id: "PGA"
  team_id: "tiger-woods"
  name: "team_tracker_tiger"
```
But that yields a "NOT_FOUND".
Also tried some other combinations, but can't figure out.
Can you help me please?

**Comment by vasqued2** [comment]
team_id:  WOODS

or "TIGER WOODS"

**Comment by brhahlen** [comment]
Awesome! That worked, thanks!
