### ISSUE TITLE
Team icons overlapping other items when viewing entity attributes

### ISSUE THREAD

**Issue by Shredder5262** [vasqued2/ha-teamtracker#97]
This seems to be a newish thing since the last few updates but the screenshot pretty much speaks for itself. The information on the team tracker card shows that icons and stats will overlap anything that should normally be in the background when looking at other cards entity info. In this example the entity i am viewing is not overlaying on the card. but in many other instances the information from the team card overlaps 
![2023-05-15 21_33_44-Andrew Dashboard – Home Assistant - Vivaldi](https://github.com/vasqued2/ha-teamtracker/assets/59770346/c2aa2299-2705-4a6b-a3c5-5aa6da060c26)

**Comment by RentreX** [comment]
https://github.com/vasqued2/ha-teamtracker-card/issues/53#issuecomment-1548749728

**Comment by vasqued2** [comment]
Upgrade the card to v0.7.3.

If it doesn't fix it, try clearing cache and refreshing. Let me know if there are still issues and on what browser/app/device, etc.

**Comment by Shredder5262** [comment]
yep, updating did the trick. Thank you for your support
